# Generated by Django 4.2.16 on 2026-08-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0001_initial'),
        ('scorecards', '0001_initial'),
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(blank=True, default='', max_length=20)),
                ('position_applied_for', models.CharField(blank=True, default='', max_length=255)),
                ('resume', models.TextField(blank=True, default='')),
                ('highest_qualification', models.CharField(blank=True, default='', max_length=255)),
                ('relevant_experience', models.CharField(blank=True, default='', max_length=50)),
                ('notice_period', models.CharField(blank=True, default='', max_length=50)),
                ('expected_ctc', models.CharField(blank=True, default='', max_length=50)),
                ('linkedin_profile', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('Invited', 'Invited'), ('In progress', 'In progress'), ('Scored', 'Scored'), ('Shortlisted', 'Shortlisted'), ('Rejected (auto)', 'Rejected (auto)'), ('Rejected', 'Rejected')], default='Invited', max_length=50)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tab_switches', models.IntegerField(default=0)),
                ('paste_events', models.IntegerField(default=0)),
                ('replay_used', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('partner_note', models.TextField(blank=True, default='')),
                ('consent_recorded', models.BooleanField(default=False)),
                ('webcam_snapshot', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='openings.jobopening')),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('job_opening', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('interview_link', models.URLField(max_length=1000)),
                ('link_expiry', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='candidates.candidate')),
            ],
            options={
                'db_table': 'invitations',
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Not Started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_round', models.IntegerField(default=0)),
                ('current_question', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0.0)),
                ('resume_info', models.JSONField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='candidates.candidate')),
                ('interview_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='flows.interviewflow')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='candidates.invitation')),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='openings.jobopening')),
                ('scorecard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scorecards.scorecard')),
            ],
            options={
                'db_table': 'interview_sessions',
            },
        ),
        migrations.CreateModel(
            name='CandidateTranscriptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('timestamp', models.CharField(max_length=20)),
                ('answer_text', models.TextField()),
                ('score_value', models.FloatField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='candidates.candidate')),
            ],
            options={
                'db_table': 'candidate_transcript_lines',
            },
        ),
        migrations.CreateModel(
            name='CandidateScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('score_value', models.FloatField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='candidates.candidate')),
            ],
            options={
                'db_table': 'candidate_score_details',
            },
        ),
    ]
