# Generated by Django 4.2.16 on 2026-08-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_id_alter_candidatescoredetail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetranscriptline',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
