# Generated by Django 4.2.16 on 2026-08-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidatetranscriptline_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='meta_info',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
