# Generated by Django 4.2.16 on 2026-08-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('firm_code', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('tan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('llp_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('alternate_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('firm_size', models.CharField(blank=True, max_length=20, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('subscription_auto_renew', models.BooleanField(default=False)),
                ('billing_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ca_firms',
                'managed': True,
            },
        ),
    ]
