# Generated by Django 4.2.16 on 2026-08-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_svg', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('project_type', models.CharField(default='internal', max_length=20)),
                ('backend_url', models.CharField(blank=True, max_length=500, null=True)),
                ('frontend_url', models.CharField(blank=True, max_length=500, null=True)),
                ('database_name', models.CharField(max_length=100)),
                ('database_host', models.CharField(blank=True, max_length=255, null=True)),
                ('database_port', models.IntegerField(default=3306)),
                ('database_username', models.CharField(blank=True, max_length=100, null=True)),
                ('database_password', models.CharField(blank=True, max_length=255, null=True)),
                ('database_type', models.CharField(default='mysql', max_length=20)),
                ('api_version', models.CharField(blank=True, max_length=10, null=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('min_plan_level', models.IntegerField(default=1)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FirmModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_module_url', models.CharField(blank=True, max_length=500, null=True)),
                ('custom_backend_url', models.CharField(blank=True, max_length=500, null=True)),
                ('database_name', models.CharField(blank=True, max_length=100, null=True)),
                ('module_status', models.CharField(default='inactive', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('assigned_users_count', models.IntegerField(default=0)),
                ('settings', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('firm', models.ForeignKey(db_column='firm_id', on_delete=django.db.models.deletion.CASCADE, to='firms.cafirm')),
                ('module', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='module_registry.module')),
                ('subscription', models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.CASCADE, to='subscriptions.firmsubscription')),
            ],
            options={
                'db_table': 'firm_modules',
                'managed': True,
            },
        ),
    ]
