# Generated by Django 4.2.16 on 2026-08-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('ai_model', models.CharField(default='flash', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='tenants.tenant')),
            ],
            options={
                'db_table': 'interview_flows',
            },
        ),
        migrations.CreateModel(
            name='FlowRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('form', 'Pre-screen form'), ('hr', 'Video — HR conversation'), ('tech', 'Video — Technical Q&A'), ('case', 'Case study (on camera)'), ('mcq', 'Knowledge test (MCQ)')], max_length=20)),
                ('dur', models.IntegerField(default=5)),
                ('order', models.IntegerField(default=0)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='flows.interviewflow')),
            ],
            options={
                'db_table': 'flow_rounds',
                'ordering': ['order'],
            },
        ),
    ]
