# Generated by Django 4.2.16 on 2026-08-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('auto_reject_threshold', models.IntegerField(default=50)),
                ('rating_scale', models.CharField(default='1-10', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='tenants.tenant')),
            ],
            options={
                'db_table': 'scorecards',
            },
        ),
        migrations.CreateModel(
            name='ScorecardParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='scorecards.scorecard')),
            ],
            options={
                'db_table': 'scorecard_parameters',
            },
        ),
    ]
