# Generated by Django 4.2.16 on 2026-08-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hr', 'HR conversation'), ('tech', 'Technical Q&A'), ('case', 'Case study'), ('mcq', 'Knowledge test (MCQ)')], max_length=10)),
                ('ask_count', models.IntegerField(default=1)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='flows.interviewflow')),
            ],
            options={
                'db_table': 'question_pools',
                'unique_together': {('flow', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PoolQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('marking_guide', models.TextField(blank=True, default='')),
                ('feeds_parameter', models.CharField(max_length=255)),
                ('source', models.CharField(default='System', max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_option', models.IntegerField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pools.questionpool')),
            ],
            options={
                'db_table': 'pool_questions',
            },
        ),
    ]
